export interface StaticExercise {
  id: string;
  name: string;
  category: string;
  difficulty: string;
  primaryMuscles: string[];
  equipment: string[];
  tutorialUrl?: string;
  instructions: string[];
  cues: string[];
}

export const STATIC_EXERCISES: StaticExercise[] = [
  {
    id: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['quads', 'glutes'],
    equipment: ['barbell', 'squat-rack'],
    tutorialUrl: 'https://www.youtube.com/watch?v=i7J5h7GpNmA',
    instructions: [
      'Set the bar on the rack at shoulder height and step under it.',
      'Position the bar across your upper traps, grip just outside shoulder width.',
      'Unrack, step back, feet shoulder-width with toes slightly out.',
      'Brace your core, take a deep breath, and descend by pushing knees out.',
      'Lower until thighs are parallel to the floor or below.',
      'Drive through your heels to stand, exhale at the top.',
    ],
    cues: ['Chest up', 'Knees track toes', 'Big breath before descent', 'Drive the floor away'],
  },
  {
    id: 'conventional-deadlift',
    name: 'Barbell Deadlift',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['hamstrings', 'glutes', 'back'],
    equipment: ['barbell'],
    tutorialUrl: 'https://www.youtube.com/watch?v=vl5a9R9CqgA',
    instructions: [
      'Stand with feet hip-width, bar over mid-foot.',
      'Hinge at the hips, grip the bar just outside your legs.',
      'Set your back flat, chest up, shoulders slightly in front of the bar.',
      'Push the floor away, keeping the bar close to your body.',
      'Lock out hips and knees simultaneously at the top.',
      'Hinge back down under control to reset.',
    ],
    cues: ['Bar stays over mid-foot', 'Lat engagement before pull', 'Push not pull', 'Hips and shoulders rise together'],
  },
  {
    id: 'bench-press',
    name: 'Barbell Bench Press',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['chest', 'triceps', 'shoulders'],
    equipment: ['barbell', 'bench'],
    tutorialUrl: 'https://www.youtube.com/watch?v=vcBig73ojpE',
    instructions: [
      'Lie on bench with eyes under the bar, feet flat on floor.',
      'Grip the bar slightly wider than shoulder width.',
      'Unrack and hold the bar over your chest with arms locked.',
      'Lower the bar to your mid-chest under control.',
      'Press back up in a slight arc to the starting position.',
      'Keep your shoulder blades pinched throughout.',
    ],
    cues: ['Arch slightly', 'Elbows at 45-75 degrees', 'Bar to lower chest', 'Drive feet into floor'],
  },
  {
    id: 'overhead-press',
    name: 'Overhead Press (OHP)',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['shoulders', 'triceps'],
    equipment: ['barbell'],
    tutorialUrl: 'https://www.youtube.com/watch?v=2yjwXTZQDDI',
    instructions: [
      'Stand with feet shoulder-width, bar resting on front delts.',
      'Grip just outside shoulder width, elbows slightly in front of bar.',
      'Brace your core and glutes hard.',
      'Press the bar straight up, moving your head back to allow clearance.',
      'Lock out overhead, bar over mid-foot.',
      'Lower under control back to shoulders.',
    ],
    cues: ['Squeeze glutes', 'Bar path is straight', 'Head through at lockout', 'Full lockout every rep'],
  },
  {
    id: 'pull-up',
    name: 'Pull-Up',
    category: 'bodyweight',
    difficulty: 'intermediate',
    primaryMuscles: ['back', 'biceps'],
    equipment: ['pull-up-bar'],
    tutorialUrl: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
    instructions: [
      'Hang from the bar with an overhand grip, hands slightly wider than shoulders.',
      'Depress your shoulder blades and engage your lats.',
      'Pull your elbows down and back until your chin clears the bar.',
      'Pause briefly at the top.',
      'Lower yourself under control to a dead hang.',
    ],
    cues: ['Elbows to hips', 'Chest to bar', 'No kipping', 'Full dead hang at bottom'],
  },
  {
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['back', 'biceps'],
    equipment: ['dumbbells', 'bench'],
    tutorialUrl: 'https://www.youtube.com/watch?v=roCP6wCXPqo',
    instructions: [
      'Place one knee and same-side hand on a bench for support.',
      'Hold a dumbbell in the opposite hand, arm hanging straight down.',
      'Row the dumbbell up toward your hip, elbow driving back.',
      'Squeeze your lat at the top for a moment.',
      'Lower the dumbbell back to full extension.',
    ],
    cues: ['Elbow close to body', 'Drive elbow, not hand', 'Full stretch at bottom', 'No torso rotation'],
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift (RDL)',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['hamstrings', 'glutes'],
    equipment: ['barbell'],
    tutorialUrl: 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
    instructions: [
      'Stand holding a barbell at hip height, feet hip-width apart.',
      'Hinge at the hips, pushing them back while keeping your back flat.',
      'Lower the bar along your legs until you feel a strong hamstring stretch.',
      'Drive your hips forward to return to standing.',
      'Keep the bar close to your body throughout.',
    ],
    cues: ['Hips back not down', 'Soft knee bend', 'Bar drags down the leg', 'Feel the stretch'],
  },
  {
    id: 'dumbbell-lunges',
    name: 'Walking Lunge',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['quads', 'glutes'],
    equipment: ['dumbbells'],
    tutorialUrl: 'https://www.youtube.com/watch?v=D7KaRcUTQeE',
    instructions: [
      'Stand tall holding a dumbbell in each hand.',
      'Step forward with one foot, lowering your back knee toward the floor.',
      'Front knee should stay over your ankle, not caving in.',
      'Push through your front heel to return to standing.',
      'Alternate legs for the desired reps.',
    ],
    cues: ['Torso upright', 'Front knee tracks toes', 'Back knee hovers above floor', 'Drive through heel'],
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['chest', 'shoulders', 'triceps'],
    equipment: ['dumbbells', 'bench'],
    tutorialUrl: 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
    instructions: [
      'Set the bench to 30-45 degrees incline.',
      'Sit with dumbbells resting on thighs, then kick them up as you lie back.',
      'Hold dumbbells at shoulder level, palms facing forward.',
      'Press them up and slightly in until arms are extended.',
      'Lower back to shoulder level under control.',
    ],
    cues: ['Chest up and out', 'Elbows at 45 degrees', 'Full range of motion', 'Controlled descent'],
  },
  {
    id: 'cable-fly',
    name: 'Cable Crossover',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['chest'],
    equipment: ['cable-machine'],
    tutorialUrl: 'https://www.youtube.com/watch?v=Iwe6AmxVf7o',
    instructions: [
      'Set cables at shoulder height and stand in the centre.',
      'Grab a handle in each hand, lean slightly forward.',
      'With a slight bend in the elbows, bring your hands together in an arc.',
      'Squeeze your chest hard at the peak contraction.',
      'Open your arms back out under control, feeling the stretch.',
    ],
    cues: ['Hug a tree motion', 'Keep elbow bend constant', 'Squeeze at centre', 'Slow eccentric'],
  },
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['triceps'],
    equipment: ['cable-machine'],
    tutorialUrl: 'https://www.youtube.com/watch?v=2-LAMcpzODU',
    instructions: [
      'Set cable to high position, attach a rope or bar.',
      'Stand facing the cable, elbows tucked to your sides.',
      'Push the handle down until your arms are fully extended.',
      'Squeeze your triceps at the bottom.',
      'Let the cable pull your hands back up under control.',
    ],
    cues: ['Elbows pinned to sides', 'Full extension', 'No forward lean', 'Control the return'],
  },
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['biceps'],
    equipment: ['barbell'],
    tutorialUrl: 'https://www.youtube.com/watch?v=kwG2ipFRgfo',
    instructions: [
      'Stand holding a barbell with an underhand grip, hands shoulder-width.',
      'Keep your elbows pinned to your sides throughout.',
      'Curl the bar up toward your chin by flexing your biceps.',
      'Squeeze at the top.',
      'Lower slowly back to full extension.',
    ],
    cues: ['No swinging', 'Elbows stay fixed', 'Full extension at bottom', 'Supinate at top'],
  },
  {
    id: 'lateral-raise',
    name: 'Lateral Raise',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['shoulders'],
    equipment: ['dumbbells'],
    tutorialUrl: 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
    instructions: [
      'Stand holding dumbbells at your sides.',
      'With a slight bend in the elbows, raise arms out to the sides.',
      'Lift until your arms are parallel to the floor.',
      'Pause briefly at the top.',
      'Lower back down slowly, resist the weight on the way down.',
    ],
    cues: ['Lead with elbows', 'Slight forward tilt', 'No shrugging', 'Slow and controlled'],
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['shoulders', 'back'],
    equipment: ['cable-machine'],
    tutorialUrl: 'https://www.youtube.com/watch?v=rep-qVOkqgk',
    instructions: [
      'Set the cable to head height with a rope attachment.',
      'Grasp the rope with both hands, step back to create tension.',
      'Pull the rope toward your face, elbows flaring high and wide.',
      'Rotate wrists outward at the end so knuckles face the ceiling.',
      'Return slowly to the start.',
    ],
    cues: ['Elbows above shoulders', 'External rotation at finish', 'Squeeze rear delts', 'Slow tempo'],
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['quads', 'glutes'],
    equipment: ['cable-machine'],
    tutorialUrl: 'https://www.youtube.com/watch?v=IZxyjW7MPJQ',
    instructions: [
      'Sit in the leg press machine, feet shoulder-width on the platform.',
      'Release the safety handles and lower the sled toward you by bending knees.',
      'Stop just before your lower back rounds off the seat.',
      'Press the platform away until legs are nearly extended.',
      'Do not lock out knees fully at the top.',
    ],
    cues: ['Feet shoulder-width', 'Knees track toes', 'No lower back rounding', 'Control descent'],
  },
  {
    id: 'leg-curl',
    name: 'Leg Curl',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['hamstrings'],
    equipment: ['cable-machine'],
    tutorialUrl: 'https://www.youtube.com/watch?v=1Tq3QdYUuHs',
    instructions: [
      'Lie face down on the leg curl machine, pad resting just above your heels.',
      'Curl your heels toward your glutes as far as possible.',
      'Squeeze your hamstrings hard at the top.',
      'Lower the weight slowly back to the start.',
    ],
    cues: ['Hips stay on pad', 'Full range of motion', 'Slow eccentric', 'Toes pointed for more stretch'],
  },
  {
    id: 'calf-raise',
    name: 'Standing Calf Raise',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['calves'],
    equipment: ['squat-rack'],
    tutorialUrl: 'https://www.youtube.com/watch?v=-M4-G8p1fCI',
    instructions: [
      'Stand on a raised surface with heels hanging off the edge.',
      'Lower your heels as far as possible to stretch the calves.',
      'Rise up on your toes as high as possible.',
      'Hold the top for a beat, squeezing the calves.',
      'Lower slowly back down.',
    ],
    cues: ['Full range - stretch to squeeze', 'Slow 3-second negative', 'Pause at top', 'Single-leg for more intensity'],
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'bodyweight',
    difficulty: 'beginner',
    primaryMuscles: ['core'],
    equipment: ['mat'],
    tutorialUrl: 'https://www.youtube.com/watch?v=ASdvN_XEl_c',
    instructions: [
      'Get into a push-up position, then lower onto your forearms.',
      'Body forms a straight line from head to heels.',
      'Brace your abs as if you are about to be punched.',
      'Squeeze your glutes and keep your hips level.',
      'Hold for the desired time, breathing steadily.',
    ],
    cues: ['Neutral spine', 'Squeeze everything', 'Do not let hips sag', 'Breathe through it'],
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    category: 'bodyweight',
    difficulty: 'beginner',
    primaryMuscles: ['chest', 'triceps', 'shoulders'],
    equipment: ['none'],
    tutorialUrl: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
    instructions: [
      'Start in a high plank, hands just outside shoulder width.',
      'Keep your body in a straight line from head to heels.',
      'Lower your chest to just above the floor by bending your elbows.',
      'Press back up to the starting position.',
      'Elbows should flare about 45 degrees from your torso.',
    ],
    cues: ['Rigid body line', 'Elbows at 45 degrees', 'Chest touches floor', 'Full lockout at top'],
  },
  {
    id: 'dip',
    name: 'Tricep Dip',
    category: 'bodyweight',
    difficulty: 'intermediate',
    primaryMuscles: ['triceps', 'chest', 'shoulders'],
    equipment: ['pull-up-bar'],
    tutorialUrl: 'https://www.youtube.com/watch?v=2z8JmcrW-As',
    instructions: [
      'Grip parallel bars and support your weight with arms locked.',
      'Lean slightly forward to target the chest more.',
      'Lower yourself by bending your elbows until upper arms are parallel to floor.',
      'Press back up to the start.',
      'Keep the movement controlled throughout.',
    ],
    cues: ['Lean for chest, upright for triceps', 'Elbows back not out', 'Full range of motion', 'No kipping'],
  },
  {
    id: 'chin-up',
    name: 'Chin-Up',
    category: 'bodyweight',
    difficulty: 'intermediate',
    primaryMuscles: ['biceps', 'back'],
    equipment: ['pull-up-bar'],
    tutorialUrl: 'https://www.youtube.com/watch?v=brhRXlOhsAM',
    instructions: [
      'Hang from the bar with an underhand grip, hands shoulder-width.',
      'Pull your chest up toward the bar by driving elbows down.',
      'Chin clears the bar at the top.',
      'Lower back to a full dead hang under control.',
    ],
    cues: ['Underhand grip = more bicep', 'Chest to bar', 'Full dead hang', 'Slow descent'],
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['quads', 'glutes', 'core'],
    equipment: ['kettlebell'],
    tutorialUrl: 'https://www.youtube.com/watch?v=MxsFDhcyFyE',
    instructions: [
      'Hold a kettlebell or dumbbell at chest height with both hands.',
      'Stand with feet shoulder-width, toes slightly out.',
      'Squat down, keeping elbows inside your knees to push them out.',
      'Descend until thighs are at least parallel to the floor.',
      'Drive through your heels to stand back up.',
    ],
    cues: ['Elbows push knees out', 'Upright torso', 'Heels flat', 'Sit between your heels'],
  },
  {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['glutes', 'hamstrings', 'core'],
    equipment: ['kettlebell'],
    tutorialUrl: 'https://www.youtube.com/watch?v=sSESeQAir2M',
    instructions: [
      'Stand with feet shoulder-width, kettlebell on the floor in front.',
      'Hike the bell back between your legs with a hip hinge.',
      'Explosively drive your hips forward to swing the bell to chest height.',
      'Let the bell float for a moment at the top.',
      'Hinge back as it falls, hike it back between your legs.',
    ],
    cues: ['Hips not squat', 'Snap hips, do not pull arms', 'Tighten at top', 'Lat engagement on descent'],
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['glutes'],
    equipment: ['barbell', 'bench'],
    tutorialUrl: 'https://www.youtube.com/watch?v=LM8XHLYJoYs',
    instructions: [
      'Sit against a bench, bar over your hips with padding.',
      'Feet flat on floor, hip-width apart.',
      'Drive through your heels and upper back to thrust hips up.',
      'At the top, hips should be level with shoulders and knees.',
      'Squeeze glutes hard at lockout, then lower under control.',
    ],
    cues: ['Chin to chest', 'Squeeze glutes at top', 'Full hip extension', 'Feet not too far'],
  },
  {
    id: 'sumo-deadlift',
    name: 'Sumo Deadlift',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['glutes', 'hamstrings', 'back'],
    equipment: ['barbell'],
    tutorialUrl: 'https://www.youtube.com/watch?v=dlDiRbUFLG0',
    instructions: [
      'Stand with feet much wider than shoulder-width, toes pointing out.',
      'Grip the bar inside your legs, shoulder-width or closer.',
      'Hinge to the bar, keeping torso more upright than conventional.',
      'Push the floor apart as you drive up.',
      'Lock out hips and knees at the top.',
    ],
    cues: ['Spread the floor', 'Upright torso', 'Bar close to shins', 'Hips drop between knees'],
  },
  {
    id: 'hack-squat',
    name: 'Hack Squat',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['quads', 'glutes'],
    equipment: ['squat-rack'],
    tutorialUrl: 'https://www.youtube.com/watch?v=EdtPBSuRfOY',
    instructions: [
      'Position yourself in the hack squat machine, back against the pad.',
      'Feet shoulder-width on the platform, toes slightly out.',
      'Release the safety handles and lower under control.',
      'Descend until thighs are past parallel.',
      'Drive through your feet to return to the top.',
    ],
    cues: ['Full depth', 'Knees track toes', 'Even pressure across foot', 'Control the descent'],
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: 'resistance',
    difficulty: 'advanced',
    primaryMuscles: ['quads', 'glutes'],
    equipment: ['dumbbells', 'bench'],
    tutorialUrl: 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
    instructions: [
      'Stand in front of a bench, place your back foot on it.',
      'Hop your front foot out until your shin is vertical at the bottom.',
      'Lower your back knee toward the floor.',
      'Front knee tracks your toes throughout.',
      'Drive through your front heel to stand.',
    ],
    cues: ['Shin vertical at bottom', 'Torso slightly forward', 'Back knee to floor', 'Front heel drives up'],
  },
  {
    id: 'seated-row',
    name: 'Seated Cable Row',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['back', 'biceps'],
    equipment: ['cable-machine'],
    tutorialUrl: 'https://www.youtube.com/watch?v=GZbfZ033f74',
    instructions: [
      'Sit at the cable row station, feet on the platform, knees slightly bent.',
      'Grab the handle, sit tall with a slight arch in your lower back.',
      'Row the handle into your lower stomach.',
      'Squeeze your shoulder blades together at the peak.',
      'Let the cable pull your arms forward under control.',
    ],
    cues: ['Chest up, no slouch', 'Row to hip, not chest', 'Squeeze blades', 'Controlled release'],
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['back', 'biceps'],
    equipment: ['cable-machine'],
    tutorialUrl: 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
    instructions: [
      'Sit at the lat pulldown machine, thighs secured under the pad.',
      'Grip the bar wider than shoulder-width, overhand.',
      'Lean back slightly and pull the bar to your upper chest.',
      'Drive your elbows down and back.',
      'Control the bar back to full arm extension.',
    ],
    cues: ['Chest up to meet the bar', 'Elbows down not back', 'Full stretch at top', 'Do not swing'],
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['shoulders', 'triceps'],
    equipment: ['dumbbells'],
    tutorialUrl: 'https://www.youtube.com/watch?v=qEwKCR5JCog',
    instructions: [
      'Sit on a bench with back support, dumbbells at shoulder height.',
      'Palms facing forward, elbows at 90 degrees.',
      'Press dumbbells up until arms are fully extended.',
      'Bring them back down to shoulder level under control.',
    ],
    cues: ['No lower back arch', 'Press slightly in at top', 'Full extension', 'Controlled descent'],
  },
  {
    id: 'dumbbell-fly',
    name: 'Dumbbell Fly',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['chest'],
    equipment: ['dumbbells', 'bench'],
    tutorialUrl: 'https://www.youtube.com/watch?v=eozdVDA78K0',
    instructions: [
      'Lie on a flat bench, dumbbells over your chest, palms facing each other.',
      'With a slight bend in the elbows, lower the dumbbells out to the sides.',
      'Feel a deep stretch across your chest at the bottom.',
      'Squeeze the chest to bring the dumbbells back together in an arc.',
    ],
    cues: ['Like hugging a barrel', 'Keep elbow angle constant', 'Deep stretch at bottom', 'Squeeze at top'],
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['biceps'],
    equipment: ['dumbbells'],
    tutorialUrl: 'https://www.youtube.com/watch?v=zC3nLlEvin4',
    instructions: [
      'Stand holding dumbbells with a neutral grip (palms facing each other).',
      'Keep your elbows tucked to your sides.',
      'Curl both dumbbells up toward your shoulders.',
      'Lower back to full extension slowly.',
    ],
    cues: ['Neutral grip throughout', 'No swinging', 'Full extension', 'Alternate or together'],
  },
  {
    id: 'skull-crusher',
    name: 'Skull Crusher',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['triceps'],
    equipment: ['barbell', 'bench'],
    tutorialUrl: 'https://www.youtube.com/watch?v=d_KZxkY_0cM',
    instructions: [
      'Lie on a bench holding a barbell or EZ-bar over your chest, arms extended.',
      'Keep your upper arms perpendicular to the floor.',
      'Lower the bar toward your forehead by bending only at the elbows.',
      'Press back to full extension.',
    ],
    cues: ['Upper arms stay fixed', 'Lower to forehead', 'Elbows in', 'Full extension'],
  },
  {
    id: 'chest-supported-row',
    name: 'Chest Supported Row',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['back'],
    equipment: ['dumbbells', 'bench'],
    tutorialUrl: 'https://www.youtube.com/watch?v=xQNrFHEMhI4',
    instructions: [
      'Set a bench to 30-45 degrees, lie face down with chest against the pad.',
      'Hold dumbbells with arms hanging straight down.',
      'Row both dumbbells up toward your hips, elbows driving back.',
      'Squeeze your shoulder blades at the top.',
      'Lower back to the hanging position.',
    ],
    cues: ['Chest stays on bench', 'No momentum', 'Squeeze at top', 'Full stretch at bottom'],
  },
  {
    id: 'box-jump',
    name: 'Box Jump',
    category: 'plyo',
    difficulty: 'intermediate',
    primaryMuscles: ['quads', 'glutes', 'calves'],
    equipment: ['box'],
    tutorialUrl: 'https://www.youtube.com/watch?v=52r_Ul5k03g',
    instructions: [
      'Stand in front of a sturdy box, feet shoulder-width.',
      'Dip into a quarter squat and swing your arms back.',
      'Explosively jump up, swinging arms forward for momentum.',
      'Land softly on the box with both feet, knees bent.',
      'Step back down carefully and reset.',
    ],
    cues: ['Soft landing', 'Arms drive the jump', 'Land balanced', 'Step down, do not jump down'],
  },
  {
    id: 'burpee',
    name: 'Burpee',
    category: 'cardio',
    difficulty: 'intermediate',
    primaryMuscles: ['core', 'chest', 'legs'],
    equipment: ['none'],
    tutorialUrl: 'https://www.youtube.com/watch?v=JZQA08SlJnM',
    instructions: [
      'Start standing, then drop your hands to the floor.',
      'Jump or step feet back into a push-up position.',
      'Perform a push-up (optional but recommended).',
      'Jump or step feet back to your hands.',
      'Explode up into a jump, clapping overhead.',
    ],
    cues: ['Full push-up for best results', 'Land soft', 'Keep a rhythm', 'Breathe on the way up'],
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climber',
    category: 'cardio',
    difficulty: 'beginner',
    primaryMuscles: ['core', 'shoulders'],
    equipment: ['none'],
    tutorialUrl: 'https://www.youtube.com/watch?v=nmwgirgXLYM',
    instructions: [
      'Start in a high plank position, core tight.',
      'Drive one knee toward your chest quickly.',
      'Immediately switch legs in a running motion.',
      'Keep your hips level throughout.',
      'Maintain a fast pace for cardio or slow for core focus.',
    ],
    cues: ['Hips level', 'Core tight', 'Do not bounce hips', 'Fast and controlled'],
  },
  {
    id: 'jump-squat',
    name: 'Jump Squat',
    category: 'plyo',
    difficulty: 'intermediate',
    primaryMuscles: ['quads', 'glutes', 'calves'],
    equipment: ['none'],
    tutorialUrl: 'https://www.youtube.com/watch?v=CVaEhXotL7M',
    instructions: [
      'Stand with feet shoulder-width apart.',
      'Squat down to at least parallel.',
      'Explode upward jumping as high as possible.',
      'Land softly with bent knees, absorbing the impact.',
      'Go directly into the next squat.',
    ],
    cues: ['Soft landing', 'Full squat depth', 'Arms help drive up', 'Knees not caving'],
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    category: 'bodyweight',
    difficulty: 'beginner',
    primaryMuscles: ['core'],
    equipment: ['mat'],
    tutorialUrl: 'https://www.youtube.com/watch?v=wkD8rjkodUI',
    instructions: [
      'Sit on the floor, knees bent, feet slightly off the ground.',
      'Lean back to about 45 degrees, keeping your spine long.',
      'Clasp your hands or hold a weight in front of your chest.',
      'Rotate your torso to one side, then the other.',
      'Keep your hips stable throughout.',
    ],
    cues: ['Rotate from the torso', 'Keep feet off floor', 'Controlled twist', 'Exhale on each twist'],
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    category: 'bodyweight',
    difficulty: 'beginner',
    primaryMuscles: ['core'],
    equipment: ['mat'],
    tutorialUrl: 'https://www.youtube.com/watch?v=4XLEnwUr1d8',
    instructions: [
      'Lie on your back, arms pointing to the ceiling, knees at 90 degrees.',
      'Press your lower back firmly into the floor.',
      'Slowly lower your right arm and left leg toward the floor.',
      'Return to start and repeat on the opposite side.',
      'Keep your lower back pressed down throughout.',
    ],
    cues: ['Lower back flat', 'Opposite arm and leg', 'Move slowly', 'Do not hold breath'],
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    category: 'bodyweight',
    difficulty: 'intermediate',
    primaryMuscles: ['core'],
    equipment: ['pull-up-bar'],
    tutorialUrl: 'https://www.youtube.com/watch?v=Pr1ieGZ5atk',
    instructions: [
      'Hang from a pull-up bar with an overhand grip.',
      'Keep your body still with no swinging.',
      'Raise your legs up until they are parallel to the floor or higher.',
      'Lower them slowly back down.',
      'For more difficulty, keep legs straight.',
    ],
    cues: ['Control the swing', 'Exhale on the way up', 'Slow descent', 'Tuck or straight for difficulty'],
  },
  {
    id: 'ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    category: 'bodyweight',
    difficulty: 'advanced',
    primaryMuscles: ['core'],
    equipment: ['none'],
    tutorialUrl: 'https://www.youtube.com/watch?v=0M8COjQ1HLY',
    instructions: [
      'Kneel on a mat holding an ab wheel with both hands.',
      'Roll forward slowly, keeping your core braced.',
      'Extend as far as you can without your hips sagging.',
      'Use your core to pull the wheel back toward your knees.',
    ],
    cues: ['Hips do not sag', 'Core does the work', 'Slow and controlled', 'Start with short range'],
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    category: 'bodyweight',
    difficulty: 'beginner',
    primaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['mat'],
    tutorialUrl: 'https://www.youtube.com/watch?v=OUgsJ8-Vi0E',
    instructions: [
      'Lie on your back, knees bent, feet flat on the floor.',
      'Drive through your heels to lift your hips toward the ceiling.',
      'Squeeze your glutes hard at the top.',
      'Hold for a second then lower back down.',
    ],
    cues: ['Squeeze glutes at top', 'Full hip extension', 'Do not hyperextend lower back', 'Slow descent'],
  },
  {
    id: 'bird-dog',
    name: 'Bird Dog',
    category: 'bodyweight',
    difficulty: 'beginner',
    primaryMuscles: ['core', 'glutes'],
    equipment: ['mat'],
    tutorialUrl: 'https://www.youtube.com/watch?v=wiFNA3sqjCA',
    instructions: [
      'Start on all fours, wrists under shoulders, knees under hips.',
      'Brace your core and extend your right arm and left leg simultaneously.',
      'Hold for 2 seconds, keeping hips level.',
      'Return and repeat on the opposite side.',
    ],
    cues: ['Hips stay square', 'Do not rotate', 'Reach long', 'Slow and deliberate'],
  },
  {
    id: 'treadmill-run',
    name: 'Treadmill Run',
    category: 'cardio',
    difficulty: 'beginner',
    primaryMuscles: ['legs', 'core'],
    equipment: ['cardio-machine'],
    tutorialUrl: 'https://www.youtube.com/watch?v=p-PXJmGGV3s',
    instructions: [
      'Set the treadmill to your desired pace and incline.',
      'Land mid-foot, not heel striking.',
      'Keep your posture upright, arms relaxed at 90 degrees.',
      'Breathe rhythmically with your strides.',
      'Cool down with a 5 minute walk.',
    ],
    cues: ['Mid-foot strike', 'Upright posture', 'Relaxed arms', 'Breathe rhythmically'],
  },
  {
    id: 'rowing-machine',
    name: 'Rowing Machine',
    category: 'cardio',
    difficulty: 'beginner',
    primaryMuscles: ['back', 'legs', 'core'],
    equipment: ['cardio-machine'],
    tutorialUrl: 'https://www.youtube.com/watch?v=H0r9jLlKoC4',
    instructions: [
      'Sit in the rower, feet strapped in, grip the handle.',
      'Push with your legs first, then lean back slightly, then pull arms.',
      'Return in reverse: arms out, lean forward, slide seat forward.',
      'The drive is legs 60%, back 20%, arms 20%.',
    ],
    cues: ['Legs then back then arms', 'Power from legs', 'Do not rush the catch', 'Maintain rhythm'],
  },
  {
    id: 'battle-ropes',
    name: 'Battle Ropes',
    category: 'cardio',
    difficulty: 'intermediate',
    primaryMuscles: ['shoulders', 'core', 'legs'],
    equipment: ['battle-ropes'],
    tutorialUrl: 'https://www.youtube.com/watch?v=Mn_gc5dFJhM',
    instructions: [
      'Stand holding the ends of two heavy ropes, feet shoulder-width.',
      'Hinge slightly at the hips, keeping a soft knee.',
      'Alternate raising and slamming each arm to create waves.',
      'Keep your core tight and breathe steadily.',
    ],
    cues: ['Drive from hips', 'Core engaged', 'Big waves not small', 'Keep moving'],
  },
  {
    id: 'sled-push',
    name: 'Sled Push',
    category: 'cardio',
    difficulty: 'intermediate',
    primaryMuscles: ['legs', 'core', 'shoulders'],
    equipment: ['sled'],
    tutorialUrl: 'https://www.youtube.com/watch?v=sAtLoXAfnN4',
    instructions: [
      'Load the sled with appropriate weight.',
      'Grip the handles at shoulder height, lean forward at 45 degrees.',
      'Drive with powerful leg strides, pushing the sled forward.',
      'Keep your back flat and core tight throughout.',
    ],
    cues: ['Low hips for power', 'Full stride extension', 'Keep moving', 'Flat back'],
  },
  {
    id: 'hip-flexor-stretch',
    name: 'Hip Flexor Stretch',
    category: 'mobility',
    difficulty: 'beginner',
    primaryMuscles: ['legs'],
    equipment: ['mat'],
    tutorialUrl: 'https://www.youtube.com/watch?v=IhF_lDTeVXA',
    instructions: [
      'Kneel on your right knee, left foot forward in a lunge position.',
      'Shift your hips forward until you feel a stretch in your right hip.',
      'Keep your torso tall, do not lean forward excessively.',
      'Hold for 30-60 seconds, then switch sides.',
    ],
    cues: ['Hips square forward', 'Squeeze back glute', 'Upright torso', 'Breathe into the stretch'],
  },
  {
    id: 'cat-cow',
    name: 'Cat-Cow',
    category: 'mobility',
    difficulty: 'beginner',
    primaryMuscles: ['back', 'core'],
    equipment: ['mat'],
    tutorialUrl: 'https://www.youtube.com/watch?v=kqnua4rHVVA',
    instructions: [
      'Start on all fours, wrists under shoulders, knees under hips.',
      'Inhale: let your belly drop, lift your head and tailbone (Cow).',
      'Exhale: round your spine toward the ceiling, tuck chin and tailbone (Cat).',
      'Flow slowly between the two positions.',
    ],
    cues: ['Breathe with movement', 'Full spinal flex and extend', 'Slow and controlled', 'Explore range'],
  },
  {
    id: 'worlds-greatest-stretch',
    name: "World's Greatest Stretch",
    category: 'mobility',
    difficulty: 'beginner',
    primaryMuscles: ['legs', 'back', 'shoulders'],
    equipment: ['none'],
    tutorialUrl: 'https://www.youtube.com/watch?v=lGUxFmjnkSM',
    instructions: [
      'Step into a deep lunge with your right foot forward.',
      'Place your right hand on the floor next to your right foot.',
      'Rotate your right arm up toward the sky, opening your chest.',
      'Hold for 2 seconds, then place your hand back down.',
      'Repeat on the other side.',
    ],
    cues: ['Sink deep into the lunge', 'Rotate fully', 'Back knee down for more stretch', 'Breathe throughout'],
  },
  {
    id: 'foam-roll-quads',
    name: 'Foam Roll Quads',
    category: 'mobility',
    difficulty: 'beginner',
    primaryMuscles: ['quads'],
    equipment: ['foam-roller'],
    tutorialUrl: 'https://www.youtube.com/watch?v=NcXUzOKkjHw',
    instructions: [
      'Lie face down with a foam roller under your left quad.',
      'Prop yourself up on your forearms.',
      'Slowly roll from just above the knee to just below the hip.',
      'Pause on any tight spots for 20-30 seconds.',
      'Switch to the other leg.',
    ],
    cues: ['Slow and deliberate', 'Breathe through discomfort', 'Pause on knots', 'Keep core tight'],
  },
  {
    id: 'pigeon-pose',
    name: 'Pigeon Pose',
    category: 'mobility',
    difficulty: 'beginner',
    primaryMuscles: ['glutes'],
    equipment: ['mat'],
    tutorialUrl: 'https://www.youtube.com/watch?v=L6yZJoZ7Eus',
    instructions: [
      'From a plank, bring your right knee forward toward your right wrist.',
      'Let your right shin rest on the floor at an angle.',
      'Extend your left leg straight back.',
      'Lower your hips toward the floor and fold forward.',
      'Hold for 60-90 seconds, then switch sides.',
    ],
    cues: ['Hips square to floor', 'Ease into the stretch', 'Breathe deeply', 'Front foot flexed'],
  },
  {
    id: 'thoracic-rotation',
    name: 'Thoracic Spine Rotation',
    category: 'mobility',
    difficulty: 'beginner',
    primaryMuscles: ['back'],
    equipment: ['mat'],
    tutorialUrl: 'https://www.youtube.com/watch?v=0oHkFc_sKU0',
    instructions: [
      'Lie on your side in the fetal position, knees stacked at 90 degrees.',
      'Place both arms out in front, palms together.',
      'Slowly rotate your top arm back, opening your chest to the ceiling.',
      'Follow with your eyes, hold for 2 seconds.',
      'Return to start and repeat for reps, then switch sides.',
    ],
    cues: ['Keep knees together', 'Rotate from the thoracic spine', 'Eyes follow hand', 'Do not force the range'],
  },
  {
    id: 'medicine-ball-slam',
    name: 'Medicine Ball Slam',
    category: 'plyo',
    difficulty: 'beginner',
    primaryMuscles: ['core', 'shoulders', 'back'],
    equipment: ['medicine-ball'],
    tutorialUrl: 'https://www.youtube.com/watch?v=1rSkAuCO4bk',
    instructions: [
      'Stand with feet shoulder-width, holding a medicine ball.',
      'Raise the ball overhead, going up on your toes.',
      'Slam the ball into the floor as hard as possible.',
      'Squat to pick it up and repeat.',
    ],
    cues: ['Full extension overhead', 'Slam with everything', 'Catch or squat to pick up', 'Core drives the slam'],
  },
  {
    id: 'depth-jump',
    name: 'Depth Jump',
    category: 'plyo',
    difficulty: 'advanced',
    primaryMuscles: ['quads', 'glutes', 'calves'],
    equipment: ['box'],
    tutorialUrl: 'https://www.youtube.com/watch?v=GSRnakMuN6I',
    instructions: [
      'Stand on a box, step off (do not jump off).',
      'As soon as your feet touch the ground, jump as high as possible immediately.',
      'Minimise ground contact time.',
      'Land softly with bent knees.',
    ],
    cues: ['Step off, do not jump off', 'Minimum ground contact', 'Explode immediately', 'Soft landing'],
  },
  {
    id: 'broad-jump',
    name: 'Broad Jump',
    category: 'plyo',
    difficulty: 'intermediate',
    primaryMuscles: ['glutes', 'quads', 'calves'],
    equipment: ['none'],
    tutorialUrl: 'https://www.youtube.com/watch?v=GMp9KpQfZkU',
    instructions: [
      'Stand with feet shoulder-width.',
      'Dip into a squat and swing your arms back.',
      'Jump forward as far as possible.',
      'Land with both feet, absorbing impact with bent knees.',
      'Stick the landing for a count of two.',
    ],
    cues: ['Arms drive the jump', 'Soft landing', 'Land and stick', 'Power from hips'],
  },
  {
    id: 'farmers-carry',
    name: "Farmer's Carry",
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['core', 'back', 'shoulders'],
    equipment: ['dumbbells'],
    tutorialUrl: 'https://www.youtube.com/watch?v=Fkzk_RqlYig',
    instructions: [
      'Pick up a heavy dumbbell or kettlebell in each hand.',
      'Stand tall with shoulders back and down.',
      'Walk forward with controlled, even steps.',
      'Keep your core braced and do not let the weights pull you sideways.',
    ],
    cues: ['Tall posture', 'Core tight', 'Do not lean', 'Short even steps'],
  },
  {
    id: 'single-leg-rdl',
    name: 'Single Leg Romanian Deadlift',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['hamstrings', 'glutes'],
    equipment: ['dumbbells'],
    tutorialUrl: 'https://www.youtube.com/watch?v=vFngPV39_uY',
    instructions: [
      'Stand on one leg, holding a dumbbell in the opposite hand.',
      'Hinge at the hip, extending your free leg back for balance.',
      'Lower the dumbbell along your standing leg.',
      'Feel a stretch in your hamstring at the bottom.',
      'Drive your hips forward to return to standing.',
    ],
    cues: ['Hip hinge, not squat', 'Back leg in line with torso', 'Soft knee on standing leg', 'Slow and balanced'],
  },
  {
    id: 'cable-kickback',
    name: 'Cable Glute Kickback',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['glutes'],
    equipment: ['cable-machine'],
    tutorialUrl: 'https://www.youtube.com/watch?v=Ex3TuXCelFo',
    instructions: [
      'Attach an ankle strap and set the cable to the lowest position.',
      'Face the cable machine and hold it for support.',
      'Keeping your torso upright, kick your leg back and up.',
      'Squeeze your glute hard at the top.',
      'Lower under control.',
    ],
    cues: ['Squeeze glute at top', 'Do not lean forward', 'Full extension', 'Slow return'],
  },
  {
    id: 'nordic-curl',
    name: 'Nordic Curl',
    category: 'bodyweight',
    difficulty: 'advanced',
    primaryMuscles: ['hamstrings'],
    equipment: ['bench'],
    tutorialUrl: 'https://www.youtube.com/watch?v=d8AAPr_NHPQ',
    instructions: [
      'Kneel with your ankles secured under something solid.',
      'Keeping your body straight from knees to head, lean forward slowly.',
      'Lower yourself as far as possible using hamstring control.',
      'Use your hands to push back up if needed.',
      'Drive your heels into the anchor to curl back up.',
    ],
    cues: ['Hips do not bend', 'Lower as slowly as possible', 'Use eccentric to build up', 'Heels drive back'],
  },
  {
    id: 'reverse-fly',
    name: 'Bent-Over Lateral Raise',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['back', 'shoulders'],
    equipment: ['dumbbells'],
    tutorialUrl: 'https://www.youtube.com/watch?v=octMzemZe68',
    instructions: [
      'Hold dumbbells and hinge forward at the hips to 45-90 degrees.',
      'With a slight bend in the elbows, raise arms out to the sides.',
      'Squeeze your rear deltoids and upper back at the top.',
      'Lower slowly back down.',
    ],
    cues: ['Lead with elbows', 'Squeeze rear delts', 'Controlled descent', 'Do not swing'],
  },
  {
    id: 'incline-curl',
    name: 'Incline Dumbbell Curl',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['biceps'],
    equipment: ['dumbbells', 'bench'],
    tutorialUrl: 'https://www.youtube.com/watch?v=soxrZlIl35U',
    instructions: [
      'Set a bench to 45-60 degrees, sit back with dumbbells hanging at your sides.',
      'Curl both dumbbells up, focusing on the long head of the bicep.',
      'Squeeze hard at the top.',
      'Lower slowly to a full stretch.',
    ],
    cues: ['Full stretch at bottom', 'Arms behind the body', 'Slow eccentric', 'No swinging'],
  },
  {
    id: 'close-grip-bench',
    name: 'Close-Grip Bench Press',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['triceps', 'chest'],
    equipment: ['barbell', 'bench'],
    tutorialUrl: 'https://www.youtube.com/watch?v=nEF0bv2FW94',
    instructions: [
      'Lie on a bench and grip the bar with hands shoulder-width or slightly closer.',
      'Lower the bar to your lower chest.',
      'Keep your elbows tucked in close to your body.',
      'Press back up to full extension.',
    ],
    cues: ['Elbows stay tucked', 'Not too close to hurt wrists', 'Full extension', 'Bar to lower chest'],
  },
  {
    id: 'arnold-press',
    name: 'Arnold Press',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['shoulders'],
    equipment: ['dumbbells'],
    tutorialUrl: 'https://www.youtube.com/watch?v=6Z15_WdXmVw',
    instructions: [
      'Sit with dumbbells at shoulder height, palms facing you.',
      'As you press up, rotate your palms to face forward.',
      'Fully extend arms overhead.',
      'Reverse the rotation as you lower back down.',
    ],
    cues: ['Smooth rotation', 'Full range of motion', 'Control the descent', 'Both directions count'],
  },
  {
    id: 'step-up',
    name: 'Dumbbell Step-Up',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['quads', 'glutes'],
    equipment: ['dumbbells', 'box'],
    tutorialUrl: 'https://www.youtube.com/watch?v=1keEpBMF7Rs',
    instructions: [
      'Hold dumbbells at your sides and stand in front of a box or bench.',
      'Step up with your right foot, driving through your heel.',
      'Bring your left foot up to meet the right.',
      'Step back down with the right foot first.',
      'Alternate leading legs.',
    ],
    cues: ['Drive through heel', 'Stay upright', 'Full extension at top', 'Controlled step down'],
  },
  {
    id: 'wall-sit',
    name: 'Wall Sit',
    category: 'bodyweight',
    difficulty: 'beginner',
    primaryMuscles: ['quads', 'glutes'],
    equipment: ['none'],
    tutorialUrl: 'https://www.youtube.com/watch?v=-cdph8hv0O0',
    instructions: [
      'Lean your back against a wall and slide down until your thighs are parallel to the floor.',
      'Knees should be directly above your ankles.',
      'Keep your back flat against the wall.',
      'Hold for the prescribed time, breathing steadily.',
    ],
    cues: ['Thighs parallel', 'Back flat', 'Knees over ankles', 'Do not hold breath'],
  },
  {
    id: 'bicycle-crunch',
    name: 'Bicycle Crunch',
    category: 'bodyweight',
    difficulty: 'beginner',
    primaryMuscles: ['core'],
    equipment: ['mat'],
    tutorialUrl: 'https://www.youtube.com/watch?v=9FGilxCbdz8',
    instructions: [
      'Lie on your back, hands behind your head.',
      'Lift your shoulders off the floor and bring one knee toward your chest.',
      'Rotate your opposite elbow toward that knee.',
      'Switch sides in a pedalling motion.',
      'Keep your lower back pressed into the floor.',
    ],
    cues: ['Rotate from the torso', 'Do not pull on neck', 'Slow and deliberate', 'Lower back stays down'],
  },
  {
    id: 'v-up',
    name: 'V-Up',
    category: 'bodyweight',
    difficulty: 'intermediate',
    primaryMuscles: ['core'],
    equipment: ['mat'],
    tutorialUrl: 'https://www.youtube.com/watch?v=7UVgs18Y1P4',
    instructions: [
      'Lie flat on your back, arms extended overhead.',
      'Simultaneously raise your legs and torso, reaching your hands toward your feet.',
      'Form a V shape at the top.',
      'Lower back down with control.',
    ],
    cues: ['Keep legs straight', 'Reach for toes', 'Slow descent', 'Breathe out on the way up'],
  },
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['chest', 'triceps'],
    equipment: ['dumbbells', 'bench'],
    tutorialUrl: 'https://www.youtube.com/watch?v=VmB1G1K7v94',
    instructions: [
      'Lie on bench holding dumbbells at chest',
      'Press up until arms extended',
      'Lower with control',
    ],
    cues: ['Neutral grip option', 'Control descent'],
  },
  {
    id: 'incline-barbell-bench-press',
    name: 'Incline Barbell Bench Press',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['upper chest', 'front delts', 'triceps'],
    equipment: ['barbell', 'bench'],
    tutorialUrl: 'https://www.youtube.com/watch?v=SrqOu55lrYU',
    instructions: [
      'Set bench to 30-45°',
      'Press bar from upper chest',
      'Lower to clavicle level',
    ],
    cues: ['Keep shoulders down', '30° angle is ideal'],
  },
  {
    id: 'decline-bench-press',
    name: 'Decline Bench Press',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['lower chest', 'triceps'],
    equipment: ['barbell', 'bench'],
    tutorialUrl: 'https://www.youtube.com/watch?v=LfyQBUKR8SE',
    instructions: [
      'Lie on decline bench',
      'Press bar from lower chest',
      'Lock out at top',
    ],
    cues: ['Anchor feet'],
  },
  {
    id: 'diamond-push-up',
    name: 'Diamond Push-Up',
    category: 'bodyweight',
    difficulty: 'intermediate',
    primaryMuscles: ['triceps', 'chest'],
    equipment: ['none'],
    tutorialUrl: 'https://www.youtube.com/watch?v=J0DnG1_S92I',
    instructions: [
      'Hands together forming diamond under chest',
      'Lower until chest touches hands',
      'Press up',
    ],
    cues: ['Keep elbows tucked'],
  },
  {
    id: 'decline-push-up',
    name: 'Decline Push-Up',
    category: 'bodyweight',
    difficulty: 'intermediate',
    primaryMuscles: ['upper chest', 'front delts'],
    equipment: ['bench'],
    tutorialUrl: 'https://www.youtube.com/watch?v=SKPab2YC8BE',
    instructions: [
      'Feet on bench, hands on floor',
      'Lower chest to floor',
      'Press back up',
    ],
    cues: ['More weight on hands'],
  },
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['upper back', 'lats', 'biceps'],
    equipment: ['barbell'],
    tutorialUrl: 'https://www.youtube.com/watch?v=FWJR5Ve8bnQ',
    instructions: [
      'Hinge at hips with flat back',
      'Grip bar shoulder width',
      'Pull bar to lower ribs',
      'Lower with control',
    ],
    cues: ['Back at 45°', 'Pull from elbows'],
  },
  {
    id: 't-bar-row',
    name: 'T-Bar Row',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['upper back', 'lats', 'rear delts'],
    equipment: ['barbell'],
    tutorialUrl: 'https://www.youtube.com/watch?v=j3Igk5nyZE4',
    instructions: [
      'Straddle bar with T-bar handle',
      'Hinge at hips',
      'Pull to chest',
      'Lower',
    ],
    cues: ['Chest up', 'Elbows back'],
  },
  {
    id: 'dead-hang',
    name: 'Dead Hang',
    category: 'mobility',
    difficulty: 'beginner',
    primaryMuscles: ['lats', 'forearms'],
    equipment: ['pull-up-bar'],
    tutorialUrl: 'https://www.youtube.com/watch?v=UX9YhDfl4jY',
    instructions: [
      'Grip bar and hang fully extended',
      'Relax shoulders',
      'Hold for time',
    ],
    cues: ['Active vs passive hang', 'Breathe'],
  },
  {
    id: 'front-raise',
    name: 'Front Raise',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['front delts'],
    equipment: ['dumbbells'],
    tutorialUrl: 'https://www.youtube.com/watch?v=-t7fuZ0KhDA',
    instructions: [
      'Hold dumbbells in front of thighs',
      'Raise arms forward to shoulder height',
      'Lower with control',
    ],
    cues: ['Palms down', 'Stop at shoulder level'],
  },
  {
    id: 'upright-row',
    name: 'Upright Row',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['traps', 'side delts'],
    equipment: ['barbell', 'dumbbells'],
    tutorialUrl: 'https://www.youtube.com/watch?v=amCU-ziHITM',
    instructions: [
      'Hold bar/dumbbells in front of thighs',
      'Pull up along body to chin',
      'Lower',
    ],
    cues: ['Lead with elbows', 'Bar close to body'],
  },
  {
    id: 'shrug',
    name: 'Shrug',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['traps'],
    equipment: ['dumbbells', 'barbell'],
    tutorialUrl: 'https://www.youtube.com/watch?v=g6qbq4a1_hU',
    instructions: [
      'Stand holding weight at sides',
      'Shrug shoulders straight up',
      'Hold at top, lower',
    ],
    cues: ["Don't roll — straight up"],
  },
  {
    id: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['biceps'],
    equipment: ['dumbbells'],
    tutorialUrl: 'https://www.youtube.com/watch?v=sAq_ocpRn_w',
    instructions: [
      'Stand with dumbbells at sides, palms forward',
      'Curl one or both to shoulders',
      'Lower',
    ],
    cues: ['Supinate at top', 'Control negative'],
  },
  {
    id: 'preacher-curl',
    name: 'Preacher Curl',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['biceps'],
    equipment: ['barbell', 'bench'],
    tutorialUrl: 'https://www.youtube.com/watch?v=fIWP-FRFNU0',
    instructions: [
      'Sit at preacher bench with arms on pad',
      'Curl bar toward shoulders',
      'Lower fully',
    ],
    cues: ["Don't lock out at bottom", 'Focus on stretch'],
  },
  {
    id: 'cable-bicep-curl',
    name: 'Cable Bicep Curl',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['biceps'],
    equipment: ['cable-machine'],
    tutorialUrl: 'https://www.youtube.com/watch?v=NFzTWp2qacE',
    instructions: [
      'Set cable to low position',
      'Grip handle and curl to shoulder',
      'Slow release',
    ],
    cues: ['Constant tension'],
  },
  {
    id: 'concentration-curl',
    name: 'Concentration Curl',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['biceps'],
    equipment: ['dumbbells'],
    tutorialUrl: 'https://www.youtube.com/watch?v=Jvj2wV0vOYU',
    instructions: [
      'Sit on bench, legs apart',
      'Brace elbow against inner thigh',
      'Curl dumbbell to shoulder',
    ],
    cues: ['Full supination', 'Squeeze peak contraction'],
  },
  {
    id: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['triceps (long head)'],
    equipment: ['dumbbells', 'cable-machine'],
    tutorialUrl: 'https://www.youtube.com/watch?v=-Vyt2QdsR7E',
    instructions: [
      'Hold dumbbell overhead with both hands',
      'Lower behind head by bending elbows',
      'Extend back up',
    ],
    cues: ['Elbows pointing forward', 'Full stretch at bottom'],
  },
  {
    id: 'tricep-kickback',
    name: 'Tricep Kickback',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['triceps'],
    equipment: ['dumbbells'],
    tutorialUrl: 'https://www.youtube.com/watch?v=6SS6K3lAwZ8',
    instructions: [
      'Hinge at hips with flat back',
      'Elbows at 90°',
      'Extend arms straight back',
    ],
    cues: ['Keep upper arm still', 'Hold contraction'],
  },
  {
    id: 'front-squat',
    name: 'Front Squat',
    category: 'resistance',
    difficulty: 'advanced',
    primaryMuscles: ['quads', 'glutes', 'upper back'],
    equipment: ['barbell', 'squat-rack'],
    tutorialUrl: 'https://www.youtube.com/watch?v=v-mQm_droOI',
    instructions: [
      'Bar on front shoulders, clean grip',
      'Sit straight down keeping torso upright',
      'Stand back up',
    ],
    cues: ['Elbows high', 'Chest up'],
  },
  {
    id: 'cable-pull-through',
    name: 'Cable Pull-Through',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['cable-machine'],
    tutorialUrl: 'https://www.youtube.com/watch?v=A7d_vE_39Yk',
    instructions: [
      'Set cable low, face away',
      'Hinge at hips holding rope between legs',
      'Thrust hips forward',
    ],
    cues: ['Hinge not squat'],
  },
  {
    id: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    category: 'resistance',
    difficulty: 'beginner',
    primaryMuscles: ['calves (soleus)'],
    equipment: ['dumbbells'],
    tutorialUrl: 'https://www.youtube.com/watch?v=JbyjNymZOt0',
    instructions: [
      'Sit with weight on knees',
      'Raise heels up',
      'Lower slowly',
    ],
    cues: ['Deep stretch at bottom'],
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    category: 'bodyweight',
    difficulty: 'beginner',
    primaryMuscles: ['obliques', 'shoulders'],
    equipment: ['mat'],
    tutorialUrl: 'https://www.youtube.com/watch?v=N_s9T326fU0',
    instructions: [
      'Lie on side, forearm on floor',
      'Lift hips forming straight line',
      'Hold for time',
    ],
    cues: ['Hips stacked', 'Shoulder over elbow'],
  },
  {
    id: 'cable-woodchop',
    name: 'Cable Woodchop',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['obliques', 'core'],
    equipment: ['cable-machine'],
    tutorialUrl: 'https://www.youtube.com/watch?v=pZapBMiC444',
    instructions: [
      'Set cable at shoulder height',
      'Stand sideways, pull diagonally across body',
      'Rotate torso, not arms',
    ],
    cues: ['Rotate from core', 'Pause at end'],
  },
  {
    id: 'assault-bike',
    name: 'Assault Bike',
    category: 'cardio',
    difficulty: 'intermediate',
    primaryMuscles: ['quads', 'glutes', 'core', 'shoulders'],
    equipment: ['cardio-machine'],
    tutorialUrl: 'https://www.youtube.com/watch?v=xV3fU2u0Nfs',
    instructions: [
      'Pedal with arms and legs',
      'Maintain steady pace or sprint',
      'Monitor calories/RPM',
    ],
    cues: ['Push and pull both handles'],
  },
  {
    id: 'jump-rope',
    name: 'Jump Rope',
    category: 'cardio',
    difficulty: 'beginner',
    primaryMuscles: ['calves', 'quads', 'shoulders'],
    equipment: ['none'],
    tutorialUrl: 'https://www.youtube.com/watch?v=u3zgHI8QnqE',
    instructions: [
      'Hold handles at hip height',
      'Jump with soft knees',
      'Swing rope with wrists',
    ],
    cues: ['Land softly', 'Wrist motion only'],
  },
  {
    id: 'childs-pose',
    name: "Child's Pose",
    category: 'mobility',
    difficulty: 'beginner',
    primaryMuscles: ['lats', 'lower back', 'hips'],
    equipment: ['mat'],
    tutorialUrl: 'https://www.youtube.com/watch?v=2MJGg-fUKh0',
    instructions: [
      'Kneel then sit back on heels',
      'Extend arms forward on floor',
      'Rest forehead on floor',
      'Breathe',
    ],
    cues: ['Widen knees for belly space'],
  },
  {
    id: 'figure-4-stretch',
    name: 'Figure-4 Stretch (Piriformis)',
    category: 'mobility',
    difficulty: 'beginner',
    primaryMuscles: ['glutes', 'piriformis', 'hips'],
    equipment: ['mat'],
    tutorialUrl: 'https://www.youtube.com/watch?v=tJnK1Y1Wz28',
    instructions: [
      'Lie on back, knees bent',
      'Cross one ankle over opposite knee',
      'Pull the bottom leg toward chest',
    ],
    cues: ['Keep head and shoulders relaxed'],
  },
  {
    id: '90-90-hip-stretch',
    name: '90/90 Hip Stretch',
    category: 'mobility',
    difficulty: 'beginner',
    primaryMuscles: ['hips', 'glutes'],
    equipment: ['mat'],
    tutorialUrl: 'https://www.youtube.com/watch?v=P_Yw8B73j0g',
    instructions: [
      'Sit with front leg bent 90° external, back leg 90° internal',
      'Lean forward over front leg',
      'Switch sides',
    ],
    cues: ['Keep both sit bones on floor'],
  },
  {
    id: 'wall-ball',
    name: 'Wall Ball',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['quads', 'glutes', 'shoulders', 'core'],
    equipment: ['medicine-ball'],
    tutorialUrl: 'https://www.youtube.com/watch?v=eqd_7h4A28A',
    instructions: [
      'Hold ball at chest, squat down',
      'Explode up and throw ball to target',
      'Catch and flow into next rep',
    ],
    cues: ['Ball and chest move together', 'Hit the target'],
  },
  {
    id: 'sled-pull',
    name: 'Sled Pull',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['upper back', 'hamstrings', 'glutes', 'core'],
    equipment: ['sled'],
    tutorialUrl: 'https://www.youtube.com/watch?v=gT_qE1R8D6w',
    instructions: [
      'Face away from sled',
      'Grip rope, walk forward, drag sled behind',
      'Maintain tension',
    ],
    cues: ['Chest up', 'Long strides'],
  },
  {
    id: 'sandbag-shoulder',
    name: 'Sandbag Shoulder',
    category: 'resistance',
    difficulty: 'intermediate',
    primaryMuscles: ['shoulders', 'core', 'glutes', 'quads'],
    equipment: ['medicine-ball'],
    tutorialUrl: 'https://www.youtube.com/watch?v=cW_q6R6V-E8',
    instructions: [
      'Squat to pick up sandbag',
      'Clean it to one shoulder',
      'Stand tall, walk or hold',
    ],
    cues: ['Use legs to lift', 'Tight core'],
  },
  {
    id: 'prowler-sprint',
    name: 'Prowler Sprint',
    category: 'cardio',
    difficulty: 'advanced',
    primaryMuscles: ['quads', 'glutes', 'hamstrings', 'calves'],
    equipment: ['sled'],
    tutorialUrl: 'https://www.youtube.com/watch?v=83Xy1L5oKEE',
    instructions: [
      'Load sled, grip handles',
      'Sprint pushing sled for distance',
      'Control stop',
    ],
    cues: ['Drive knees', 'Stay low'],
  },
];

const ALL_EXERCISE_TUTORIALS: Record<string, string> = {
  // Chest
  'barbell bench press': 'https://www.youtube.com/watch?v=vcBig73ojpE',
  'bench press': 'https://www.youtube.com/watch?v=vcBig73ojpE',
  'dumbbell bench press': 'https://www.youtube.com/watch?v=VmB1G1K7v80',
  'incline barbell bench press': 'https://www.youtube.com/watch?v=SrqOu55lrYU',
  'incline dumbbell press': 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
  'decline bench press': 'https://www.youtube.com/watch?v=LfyQBUKR8SE',
  'dumbbell fly': 'https://www.youtube.com/watch?v=eozdVDA78K0',
  'cable crossover': 'https://www.youtube.com/watch?v=Iwe6AmxVf7o',
  'pushup': 'https://www.youtube.com/watch?v=IODxDxX7oi4',
  'push up': 'https://www.youtube.com/watch?v=IODxDxX7oi4',
  'diamond pushup': 'https://www.youtube.com/watch?v=J0DnG1_S92I',
  'diamond push up': 'https://www.youtube.com/watch?v=J0DnG1_S92I',
  'decline pushup': 'https://www.youtube.com/watch?v=SKPab2YC8BE',
  'decline push up': 'https://www.youtube.com/watch?v=SKPab2YC8BE',

  // Back
  'barbell deadlift': 'https://www.youtube.com/watch?v=vl5a9R9CqgA',
  'deadlift': 'https://www.youtube.com/watch?v=vl5a9R9CqgA',
  'pullup': 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
  'pull up': 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
  'lat pulldown': 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
  'barbell row': 'https://www.youtube.com/watch?v=FWJR5YbTboU',
  'bent over row': 'https://www.youtube.com/watch?v=FWJR5YbTboU',
  'seated cable row': 'https://www.youtube.com/watch?v=GZbfZ033f74',
  'seated row': 'https://www.youtube.com/watch?v=GZbfZ033f74',
  'dumbbell row': 'https://www.youtube.com/watch?v=roCP6wCXPqo',
  'tbar row': 'https://www.youtube.com/watch?v=j3Igk5nyZE4',
  't bar row': 'https://www.youtube.com/watch?v=j3Igk5nyZE4',
  'face pull': 'https://www.youtube.com/watch?v=rep-qVOkqgk',
  'dead hang': 'https://www.youtube.com/watch?v=_LxFwZ1p33E',
  'chest supported row': 'https://www.youtube.com/watch?v=xQNrFHEMhI4',

  // Shoulders
  'overhead press ohp': 'https://www.youtube.com/watch?v=2yjwXTZQDDI',
  'overhead press': 'https://www.youtube.com/watch?v=2yjwXTZQDDI',
  'ohp': 'https://www.youtube.com/watch?v=2yjwXTZQDDI',
  'dumbbell shoulder press': 'https://www.youtube.com/watch?v=qEwKCR5JCog',
  'lateral raise': 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
  'front raise': 'https://www.youtube.com/watch?v=-t7fuZ0KhDA',
  'bentover lateral raise': 'https://www.youtube.com/watch?v=ttvfGg9d070',
  'bent over lateral raise': 'https://www.youtube.com/watch?v=ttvfGg9d070',
  'arnold press': 'https://www.youtube.com/watch?v=6Z15_WdxmVw',
  'upright row': 'https://www.youtube.com/watch?v=amCU-ziHITM',
  'shrug': 'https://www.youtube.com/watch?v=cJRVVxmytaM',

  // Arms
  'barbell curl': 'https://www.youtube.com/watch?v=kwG2ipFRgfo',
  'bicep curl': 'https://www.youtube.com/watch?v=kwG2ipFRgfo',
  'dumbbell curl': 'https://www.youtube.com/watch?v=sAq_ocpRh_I',
  'hammer curl': 'https://www.youtube.com/watch?v=zC3nLlEvin4',
  'preacher curl': 'https://www.youtube.com/watch?v=fIWP-FRFNU0',
  'cable bicep curl': 'https://www.youtube.com/watch?v=AsAVbk76a5w',
  'concentration curl': 'https://www.youtube.com/watch?v=Jvj2wV0vOYU',
  'closegrip bench press': 'https://www.youtube.com/watch?v=nEF0bv2fw94',
  'close grip bench press': 'https://www.youtube.com/watch?v=nEF0bv2fw94',
  'tricep pushdown': 'https://www.youtube.com/watch?v=2-LAMcpzODU',
  'overhead tricep extension': 'https://www.youtube.com/watch?v=_gsU15g15is',
  'skull crusher': 'https://www.youtube.com/watch?v=d_KZxkY_0cM',
  'tricep kickback': 'https://www.youtube.com/watch?v=6SS6K3lAwZ8',
  'tricep dip': 'https://www.youtube.com/watch?v=2z8JmcrW-As',
  'dip': 'https://www.youtube.com/watch?v=2z8JmcrW-As',
  'chinup': 'https://www.youtube.com/watch?v=brhRXlOhsAM',
  'chin up': 'https://www.youtube.com/watch?v=brhRXlOhsAM',

  // Legs
  'barbell back squat': 'https://www.youtube.com/watch?v=i7J5h7GpNmA',
  'back squat': 'https://www.youtube.com/watch?v=i7J5h7GpNmA',
  'squat': 'https://www.youtube.com/watch?v=i7J5h7GpNmA',
  'front squat': 'https://www.youtube.com/watch?v=v-mqmOWcRey',
  'leg press': 'https://www.youtube.com/watch?v=IZxyjW7MPJQ',
  'bulgarian split squat': 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
  'goblet squat': 'https://www.youtube.com/watch?v=MxsFDhcyFyE',
  'walking lunge': 'https://www.youtube.com/watch?v=D7KaRcUTQeE',
  'dumbbell lunges': 'https://www.youtube.com/watch?v=D7KaRcUTQeE',
  'lunge': 'https://www.youtube.com/watch?v=D7KaRcUTQeE',
  'romanian deadlift rdl': 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
  'romanian deadlift': 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
  'rdl': 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
  'leg curl': 'https://www.youtube.com/watch?v=1Tq3QdYUuHs',
  'hip thrust': 'https://www.youtube.com/watch?v=LM8XHLYJoYs',
  'glute bridge': 'https://www.youtube.com/watch?v=OUgsJ8-Vi0E',
  'cable pullthrough': 'https://www.youtube.com/watch?v=A0z6vC32k3s',
  'cable pull through': 'https://www.youtube.com/watch?v=A0z6vC32k3s',
  'standing calf raise': 'https://www.youtube.com/watch?v=-M4-G8p1fCI',
  'calf raise': 'https://www.youtube.com/watch?v=-M4-G8p1fCI',
  'seated calf raise': 'https://www.youtube.com/watch?v=JbyjNymZOt0',
  'sumo deadlift': 'https://www.youtube.com/watch?v=dlDiRbUFLG0',
  'hack squat': 'https://www.youtube.com/watch?v=EdtPBSuRfOY',

  // Core & Cardio & Plyo & Mobility
  'plank': 'https://www.youtube.com/watch?v=ASdvN_XEl_c',
  'side plank': 'https://www.youtube.com/watch?v=N_q-jGqd368',
  'cable woodchop': 'https://www.youtube.com/watch?v=pApyJzB4_4w',
  'dead bug': 'https://www.youtube.com/watch?v=4XLEnwUr1d8',
  'hanging leg raise': 'https://www.youtube.com/watch?v=Pr1ieGZ5atk',
  'russian twist': 'https://www.youtube.com/watch?v=wkD8rjkodUI',
  'ab wheel rollout': 'https://www.youtube.com/watch?v=0M8COjQ1HLY',
  'bird dog': 'https://www.youtube.com/watch?v=wiFNA3sqjCA',
  'treadmill run': 'https://www.youtube.com/watch?v=p-PXJmGGV3s',
  'rowing machine': 'https://www.youtube.com/watch?v=H0r9jLlKoC4',
  'assault bike': 'https://www.youtube.com/watch?v=xV3fU2u0Nfs',
  'jump rope': 'https://www.youtube.com/watch?v=u3zgHI8QnqE',
  'box jump': 'https://www.youtube.com/watch?v=52r_Ul5k03g',
  'burpee': 'https://www.youtube.com/watch?v=JZQA08SlJnM',
  'broad jump': 'https://www.youtube.com/watch?v=0l-2mBsmP74',
  'kettlebell swing': 'https://www.youtube.com/watch?v=sSESeQAir2M',
  'medicine ball slam': 'https://www.youtube.com/watch?v=g4m6EeqT42U',
  'mountain climber': 'https://www.youtube.com/watch?v=nmwgirgXLYM',
  'worlds greatest stretch': 'https://www.youtube.com/watch?v=-Vj6Jp6Y74g',
  'catcow': 'https://www.youtube.com/watch?v=w_UKcI1F2Sc',
  'cat cow': 'https://www.youtube.com/watch?v=w_UKcI1F2Sc',
  'childs pose': 'https://www.youtube.com/watch?v=2MJGg-fUKh0',
  'figure4 stretch piriformis': 'https://www.youtube.com/watch?v=tJnK1Y1Wz28',
  '9090 hip stretch': 'https://www.youtube.com/watch?v=P_Yw8B73j0g',
  'thoracic spine rotation': 'https://www.youtube.com/watch?v=Gj4bVv1uXW8',
  'wall ball': 'https://www.youtube.com/watch?v=eqd_7h4A28A',
  'sled push': 'https://www.youtube.com/watch?v=2P_KkS98E2E',
  'sled pull': 'https://www.youtube.com/watch?v=gT_qE1R8D6w',
  'farmers carry': 'https://www.youtube.com/watch?v=Fkzk_RqlYig',
  'farmer carry': 'https://www.youtube.com/watch?v=Fkzk_RqlYig',
  'battle ropes': 'https://www.youtube.com/watch?v=Mn_gc5dFJhM',
  'sandbag shoulder': 'https://www.youtube.com/watch?v=cW_q6R6V-E8',
  'prowler sprint': 'https://www.youtube.com/watch?v=83Xy1L5oKEE',
  'jump squat': 'https://www.youtube.com/watch?v=CVaEhXotL7M',
};

const TUTORIAL_URL_BY_NAME = new Map(
  STATIC_EXERCISES.map((ex) => [ex.name, ex.tutorialUrl]),
);

function normalizeName(str: string): string {
  return str.toLowerCase().replace(/[^a-z0-9]/g, '');
}

/** Curated tutorial URL for an exercise, preferring a DB-provided URL. */
export function getTutorialUrl(name: string, dbUrl?: string | null): string | undefined {
  if (dbUrl) return dbUrl;
  const staticMatch = TUTORIAL_URL_BY_NAME.get(name);
  if (staticMatch) return staticMatch;

  const key = normalizeName(name);
  for (const [dictKey, url] of Object.entries(ALL_EXERCISE_TUTORIALS)) {
    if (normalizeName(dictKey) === key || key.includes(normalizeName(dictKey))) {
      return url;
    }
  }
  return undefined;
}

/** Extract the video ID from a YouTube watch/share/embed/shorts URL. */
export function extractYouTubeId(url: string): string | null {
  const patterns = [
    /youtu\.be\/([^?&]+)/,
    /youtube\.com\/watch\?v=([^&]+)/,
    /youtube\.com\/embed\/([^?&]+)/,
    /youtube\.com\/shorts\/([^?&]+)/,
  ];
  for (const p of patterns) {
    const m = url.match(p);
    if (m) return m[1];
  }
  return null;
}

/** YouTube thumbnail for an exercise, when a curated video exists. */
export function getExerciseThumb(name: string, dbUrl?: string | null): string | null {
  const url = getTutorialUrl(name, dbUrl);
  if (url) {
    const id = extractYouTubeId(url);
    if (id) return `https://i.ytimg.com/vi/${id}/hqdefault.jpg`;
  }
  // High-quality fallback fitness image thumbnail if no video ID matched
  return `https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80`;
}

